// Copyright 1986-2026 Altair Engineering Inc.
// SPDX-License-Identifier: MIT

use std::collections::HashMap;
use crate::model::*;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const SEP: &str = "#---1----|----2----|----3----|----4----|----5----|----6----|----7----|----8----|----9----|---10----|\n";

/// Format a float in 20-char right-justified column (Radioss standard width)
fn fw(v: f64) -> String {
    // Use scientific with enough digits to be exact; Radioss accepts any float notation
    format!("{:>20.8E}", v)
}

/// Format an integer in 10-char right-justified column
fn fi(v: u32) -> String { format!("{:>10}", v) }

fn sep(o: &mut String) { o.push_str(SEP); }

// ---------------------------------------------------------------------------
// Starter deck
// ---------------------------------------------------------------------------
pub fn write_starter(model: &Model, stem: &str) -> String {
    let mut o = String::with_capacity(1 << 20);

    // ----- Header ----------------------------------------------------------
    o.push_str("#RADIOSS STARTER\n");
    o.push_str("# Input deck generated by inp2rad Rust converter\n");
    o.push_str("# REPORT ISSUES: https://github.com/OpenRadioss/Tools/discussions\n");
    o.push_str("/BEGIN\n");
    o.push_str(stem);
    o.push('\n');
    o.push_str("      2025         0\n");
    o.push_str("                  Mg                  mm                   s\n");
    o.push_str("                  Mg                  mm                   s\n");

    // ----- Assign sequential IDs ------------------------------------------
    // mat_id: material name → id
    let mat_ids: HashMap<&str, u32> = model.materials.iter().enumerate()
        .map(|(i, (n, _))| (n.as_str(), (i + 1) as u32))
        .collect();

    // prop_id: section index → id (one property per section)
    let prop_ids: Vec<u32> = (1..=model.sections.len() as u32).collect();

    // section lookup: elset name → (section index, prop_id)
    let sec_by_elset: HashMap<&str, (usize, u32)> = model.sections.iter().enumerate()
        .map(|(i, s)| (s.elset.as_str(), (i, prop_ids[i])))
        .collect();

    // grnod_id: nset index → id (start after last prop_id)
    let grnod_base = prop_ids.last().copied().unwrap_or(0) + 1;
    let nset_ids: HashMap<&str, u32> = model.nsets.iter().enumerate()
        .map(|(i, (n, _))| (n.as_str(), grnod_base + i as u32))
        .collect();

    // surf_id: surface index → id
    let surf_base = nset_ids.values().max().copied().unwrap_or(grnod_base) + 1;
    let surf_ids: HashMap<&str, u32> = model.surfaces.iter().enumerate()
        .map(|(i, s)| (s.name.as_str(), surf_base + i as u32))
        .collect();

    // inter_base: first interface ID
    let inter_base = surf_ids.values().max().copied().unwrap_or(surf_base) + 1;

    // fct_base: first function ID
    let fct_base = inter_base + model.contacts.len() as u32 + model.ties.len() as u32 + 1;

    // ----- Materials -------------------------------------------------------
    sep(&mut o);
    o.push_str("#- MATERIALS\n");
    for (name, mat) in &model.materials {
        let mid = mat_ids[name.as_str()];
        sep(&mut o);
        if !mat.plastic.is_empty() {
            write_plas_tab(&mut o, mid, name, mat);
        } else if let Some(c10) = mat.neo_hooke_c10 {
            write_neo_hooke(&mut o, mid, name, mat.rho, c10);
        } else {
            write_elast(&mut o, mid, name, mat);
        }
    }

    // ----- Properties ------------------------------------------------------
    sep(&mut o);
    o.push_str("#- PROPERTIES\n");
    for (i, sec) in model.sections.iter().enumerate() {
        let pid = prop_ids[i];
        sep(&mut o);
        match &sec.kind {
            SectionKind::Shell(thk) | SectionKind::Membrane(thk) => {
                let iplas = if matches!(sec.kind, SectionKind::Shell(_)) { 1 } else { 0 };
                o.push_str(&format!("/PROP/SHELL/{pid}\n"));
                o.push_str(&sec.elset); o.push('\n');
                o.push_str("#   Ishell    Ismstr     Ish3n    Idrill                            P_thick_fail\n");
                o.push_str("        24        -1         1         0                                       0\n");
                o.push_str("#                 hm                  hf                  hr                  dm                  dn\n");
                o.push_str("                   0                   0                   0                   0                .015\n");
                o.push_str("#        N                         Thick              Ashear              Ithick     Iplas\n");
                o.push_str(&format!("         5{}{:>20}                .833                   1{:>10}\n",
                    fw(*thk), "", iplas));
            }
            SectionKind::Solid => {
                o.push_str(&format!("/PROP/SOLID/{pid}\n"));
                o.push_str(&sec.elset); o.push('\n');
                o.push_str("#   Isolid    Ismstr               Icpre  Itetra10     Inpts   Itetra4    Iframe                  dn\n");
                o.push_str("        24        -1                  -1         2         0         3        -1                  .1\n");
                o.push_str("#                q_a                 q_b                   h            LAMBDA_V                MU_V\n");
                o.push_str("                 1.1                 .05                   0                   0                   0\n");
                o.push_str("#             dt_min            Vdef_min            Vdef_max             ASP_max             COL_min\n");
                o.push_str("                 0.0                0.01               100.0               100.0                0.01\n");
                o.push_str("#     Ndir sphpartID  Icontrol\n");
                o.push_str("                             1\n");
            }
            SectionKind::Cohesive => {
                o.push_str(&format!("/PROP/TYPE43/{pid}\n"));
                o.push_str(&sec.elset); o.push('\n');
                o.push_str("#   Ismstr                                                                            True_Thickness\n");
                o.push_str("        -1\n");
            }
        }
    }

    // ----- Parts -----------------------------------------------------------
    sep(&mut o);
    o.push_str("#- PARTS\n");
    for (i, sec) in model.sections.iter().enumerate() {
        let pid = prop_ids[i];
        let mid = sec_mat_id(&sec.material, &mat_ids);
        sep(&mut o);
        o.push_str(&format!("/PART/{pid}\n"));
        o.push_str(&sec.elset); o.push('\n');
        o.push_str(&format!("{}{}\n", fi(mid), fi(pid)));
    }

    // ----- Nodes -----------------------------------------------------------
    sep(&mut o);
    o.push_str("#- NODES\n");
    sep(&mut o);
    o.push_str("/NODE\n");
    o.push_str("#   NODEID                   X                   Y                   Z\n");
    for n in &model.nodes {
        o.push_str(&format!("{}{}{}{}\n", fi(n.id), fw(n.x), fw(n.y), fw(n.z)));
    }

    // ----- Elements --------------------------------------------------------
    sep(&mut o);
    o.push_str("#- ELEMENTS\n");
    for block in &model.elem_blocks {
        // Resolve property ID via section lookup (by elset name)
        let pid = sec_by_elset.get(block.elset.as_str()).map(|(_, pid)| *pid).unwrap_or(1);
        sep(&mut o);
        o.push_str(&format!("# {} elements for ELSET: {}\n", block.kind.rad_kw(), block.elset));
        sep(&mut o);
        o.push_str(&format!("/{}/{pid}\n", block.kind.rad_kw()));
        for el in &block.elems {
            // Radioss accepts all nodes on one line regardless of count.
            let mut line = fi(el.id);
            for &nd in &el.nodes { line.push_str(&fi(nd)); }
            o.push_str(&line);
            o.push('\n');
        }
    }

    // ----- Node groups (GRNOD) --------------------------------------------
    sep(&mut o);
    o.push_str("#- NODE GROUPS (GRNOD)\n");
    for (name, ids) in &model.nsets {
        let gid = nset_ids[name.as_str()];
        sep(&mut o);
        o.push_str(&format!("/GRNOD/NODE/{gid}\n{name}\n"));
        o.push_str("#   NODEID\n");
        for chunk in ids.chunks(10) {
            let row: String = chunk.iter().map(|&id| fi(id)).collect();
            o.push_str(&row); o.push('\n');
        }
    }

    // ----- Surfaces --------------------------------------------------------
    if !model.surfaces.is_empty() {
        sep(&mut o);
        o.push_str("#- SURFACES\n");
        for surf in &model.surfaces {
            let sid = surf_ids[surf.name.as_str()];
            sep(&mut o);
            if surf.node_type {
                // Node surface → /GRNOD/NODE referencing nset
                o.push_str(&format!("/GRNOD/NODE/{sid}\n{}\n", surf.name));
            } else {
                // Element surface → /SURF/PART referencing elsets
                o.push_str(&format!("/SURF/PART/{sid}\n{}\n", surf.name));
                o.push_str("#  PART_id\n");
                for (elset, _face) in &surf.entries {
                    // Map elset to prop_id (part id)
                    if let Some((_, pid)) = sec_by_elset.get(elset.as_str()) {
                        o.push_str(&format!("{}\n", fi(*pid)));
                    } else {
                        o.push_str(&format!("# unresolved elset: {elset}\n"));
                    }
                }
            }
        }
    }

    // ----- Boundary conditions --------------------------------------------
    sep(&mut o);
    o.push_str("#- BOUNDARY CONDITIONS\n");
    // Group boundaries: zero-value non-amplitude → /BCS, rest → /IMPDISP
    for bc in &model.boundaries {
        sep(&mut o);
        let gid = nset_ids.get(bc.nset.as_str()).copied().unwrap_or(0);
        if bc.amplitude.is_empty() && bc.value == 0.0 {
            // Static constraint → /BCS
            o.push_str(&format!("/BCS/{gid}\n{}\n", bc.nset));
            o.push_str("#  Tra  Tra  Tra  Rot  Rot  Rot  skew_ID\n");
            let [tx, ty, tz, rx, ry, rz] = bc.mask;
            o.push_str(&format!("{:>5}{:>5}{:>5}{:>5}{:>5}{:>5}         0\n",
                tx, ty, tz, rx, ry, rz));
        } else {
            // Prescribed displacement → /IMPDISP
            let fid = fct_base; // simplification: use first function
            o.push_str(&format!("/IMPDISP/{fid}/{gid}\n{}\n", bc.nset));
            o.push_str("#  Tra  Tra  Tra  Rot  Rot  Rot  skew_ID\n");
            let [tx, ty, tz, rx, ry, rz] = bc.mask;
            o.push_str(&format!("{:>5}{:>5}{:>5}{:>5}{:>5}{:>5}         0\n",
                tx, ty, tz, rx, ry, rz));
            o.push_str(&format!("#              Scale\n{}\n", fw(bc.value)));
        }
    }

    // ----- Functions (amplitudes) -----------------------------------------
    if !model.amplitudes.is_empty() {
        sep(&mut o);
        o.push_str("#- FUNCTIONS\n");
        for (fi_idx, (name, pts)) in model.amplitudes.iter().enumerate() {
            let fid = fct_base + fi_idx as u32;
            sep(&mut o);
            o.push_str(&format!("/FUNCT/{fid}\n{name}\n"));
            o.push_str("#                  X                   Y\n");
            for &(x, y) in pts {
                o.push_str(&format!("{}{}\n", fw(x), fw(y)));
            }
        }
    }

    // ----- Tied contacts (/INTER/TYPE2) ------------------------------------
    if !model.ties.is_empty() {
        sep(&mut o);
        o.push_str("#- TIED INTERFACES\n");
        for (ti, tie) in model.ties.iter().enumerate() {
            let iid = inter_base + ti as u32;
            let master_id = surf_ids.get(tie.master.as_str())
                .or_else(|| nset_ids.get(tie.master.as_str()))
                .copied().unwrap_or(0);
            let slave_id = surf_ids.get(tie.slave.as_str())
                .or_else(|| nset_ids.get(tie.slave.as_str()))
                .copied().unwrap_or(0);
            sep(&mut o);
            o.push_str(&format!("/INTER/TYPE2/{iid}\n{}\n", tie.name));
            o.push_str("#    Idmast    Idslave    Istf\n");
            o.push_str(&format!("{}{}{:>10}\n", fi(master_id), fi(slave_id), 4));
        }
    }

    // ----- Contact interfaces (/INTER/TYPE7) ------------------------------
    if !model.contacts.is_empty() {
        sep(&mut o);
        o.push_str("#- CONTACT INTERFACES\n");
        for (ci, c) in model.contacts.iter().enumerate() {
            let iid = inter_base + model.ties.len() as u32 + ci as u32;
            let master_id = surf_ids.get(c.master.as_str())
                .or_else(|| nset_ids.get(c.master.as_str()))
                .copied().unwrap_or(0);
            let slave_id = surf_ids.get(c.slave.as_str())
                .or_else(|| nset_ids.get(c.slave.as_str()))
                .copied().unwrap_or(0);
            sep(&mut o);
            o.push_str(&format!("/INTER/TYPE7/{iid}\n{}\n", c.name));
            o.push_str("#    Isearch    Iself_c   I_thick    Iedge     Spotflag\n");
            o.push_str("         2          0          0          0         27\n");
            o.push_str(&format!("#    Master_id    Slave_id  Istf\n{}{}{:>10}\n",
                fi(master_id), fi(slave_id), 3));
            o.push_str(&format!("#{}FRIC\n{}\n",
                " ".repeat(64), fw(c.friction)));
        }
    }

    // ----- Footer ---------------------------------------------------------
    sep(&mut o);
    o.push_str("/END\n");
    sep(&mut o);
    o
}

// ---------------------------------------------------------------------------
// Engine deck  (_0001.rad)
// ---------------------------------------------------------------------------
pub fn write_engine(model: &Model, stem: &str) -> String {
    let anim_dt = model.run_time / 100.0;
    let th_dt   = anim_dt / 100.0;
    format!(
        "#RADIOSS ENGINE\n\
         # Engine deck generated by inp2rad Rust converter — verify before running!\n\
         # REPORT ISSUES: https://github.com/OpenRadioss/Tools/discussions\n\
         /RUN/{stem}/1\n\
         {}\n\
         /DT\n\
         #    Tsca      Tmin\n\
         {}{}\n\
         /STOP\n\
         -1\n\
         /ANIM/DT\n\
         {}\n\
         /ANIM/ELEM/EPSP\n\
         /ANIM/ELEM/VONM\n\
         /ANIM/NODA/DV\n\
         /ANIM/NODA/VECT/VEL\n\
         /TH/DT\n\
         {}\n\
         /END\n",
        fw(model.run_time),
        fw(0.67),
        fw(model.dt),
        fw(anim_dt),
        fw(th_dt),
    )
}

// ---------------------------------------------------------------------------
// Material writers
// ---------------------------------------------------------------------------

fn write_elast(o: &mut String, mid: u32, name: &str, mat: &Material) {
    o.push_str(&format!("/MAT/ELAST/{mid}\n{name}\n"));
    o.push_str("#              RHO_I\n");
    o.push_str(&format!("{}                   0\n", fw(mat.rho)));
    o.push_str("#                  E                  nu\n");
    o.push_str(&format!("{}{}\n", fw(mat.e), fw(mat.nu)));
}

fn write_plas_tab(o: &mut String, mid: u32, name: &str, mat: &Material) {
    o.push_str(&format!("/MAT/PLAS_TAB/{mid}\n{name}\n"));
    o.push_str("#              RHO_I\n");
    o.push_str(&format!("{}                   0\n", fw(mat.rho)));
    o.push_str("#                  E                  nu           Eps_p_max               Eps_t               Eps_m\n");
    o.push_str(&format!("{}{}                   0                   0                   0\n", fw(mat.e), fw(mat.nu)));
    o.push_str("#  N_funct  F_smooth              C_hard               F_cut               Eps_f                  VP\n");
    o.push_str("         1         0                   0                   0                   0                   0\n");
    o.push_str(&format!("#  fct_IDp              Fscale\n{:>10}                   1\n", mid + 1000));
    o.push_str("#          Eps_dot_1\n                   0\n");
    // Inline the yield function data
    o.push_str(&format!("/FUNCT/{}\n{name} - yield\n", mid + 1000));
    o.push_str("#          Eps_p_true            Sig_true\n");
    for &(sig, eps) in &mat.plastic {
        o.push_str(&format!("{}{}\n", fw(eps), fw(sig)));
    }
}

fn write_neo_hooke(o: &mut String, mid: u32, name: &str, rho: f64, c10: f64) {
    o.push_str(&format!("/MAT/LAW42/{mid}\n{name}\n"));
    o.push_str("#              RHO_I\n");
    o.push_str(&format!("{}                   0\n", fw(rho)));
    o.push_str("#                 Nu\n");
    o.push_str("               0.495\n");
    o.push_str("#               Mu_1\n");
    // In Neo-Hookean: C10 = Mu/2,  so Mu = 2*C10
    o.push_str(&format!("{}\n", fw(c10 * 2.0)));
    o.push_str("\n#            alpha_1\n                 2.0\n");
}

// ---------------------------------------------------------------------------
// Helper: resolve material id (return 0 if not found)
// ---------------------------------------------------------------------------
fn sec_mat_id(mat_name: &str, mat_ids: &HashMap<&str, u32>) -> u32 {
    mat_ids.get(mat_name).copied().unwrap_or(0)
}
